/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { Postmortem } from '../types';
import { FileText, AlertOctagon, Search, Clock, Compass, CheckCircle2, ChevronRight, Activity } from 'lucide-react';

interface PostmortemSectionProps {
  postmortem: Postmortem;
}

export const PostmortemSection: React.FC<PostmortemSectionProps> = ({ postmortem }) => {
  return (
    <div className="space-y-6">
      {/* Intro Header */}
      <div className="flex items-center gap-3 border-b border-zinc-200 pb-4">
        <div className="p-2 bg-zinc-900 rounded-md text-white">
          <FileText className="w-5 h-5" />
        </div>
        <div>
          <h3 className="text-base font-mono font-bold uppercase tracking-tight text-zinc-900">
            System Postmortem & Incident Review
          </h3>
          <p className="text-xs text-zinc-500 font-sans mt-0.5">
            Post-incident analysis generated by ResolveOps Agent. Verified as complete.
          </p>
        </div>
      </div>

      {/* Grid for Summary and Customer Impact */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <div className="bg-white p-4 rounded-lg border border-zinc-200 shadow-xxs">
          <div className="flex items-center gap-2 mb-2">
            <Activity className="w-4 h-4 text-zinc-700" />
            <h4 className="text-xs font-mono font-bold uppercase text-zinc-800 tracking-wider">
              Executive Summary
            </h4>
          </div>
          <p className="text-sm text-zinc-600 leading-relaxed font-sans">{postmortem.summary}</p>
        </div>

        <div className="bg-white p-4 rounded-lg border border-zinc-200 shadow-xxs">
          <div className="flex items-center gap-2 mb-2">
            <AlertOctagon className="w-4 h-4 text-zinc-700" />
            <h4 className="text-xs font-mono font-bold uppercase text-zinc-800 tracking-wider">
              Customer Impact
            </h4>
          </div>
          <p className="text-sm text-zinc-600 leading-relaxed font-sans">{postmortem.customerImpact}</p>
        </div>
      </div>

      {/* Root Cause and Resolution */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <div className="bg-white p-4 rounded-lg border border-zinc-200 shadow-xxs">
          <div className="flex items-center gap-2 mb-2">
            <Search className="w-4 h-4 text-zinc-700" />
            <h4 className="text-xs font-mono font-bold uppercase text-zinc-800 tracking-wider">
              Root Cause
            </h4>
          </div>
          <p className="text-sm text-zinc-600 leading-relaxed font-sans font-mono bg-zinc-50 p-2.5 border border-zinc-200 rounded text-xs">
            {postmortem.rootCause}
          </p>
        </div>

        <div className="bg-white p-4 rounded-lg border border-zinc-200 shadow-xxs">
          <div className="flex items-center gap-2 mb-2">
            <CheckCircle2 className="w-4 h-4 text-green-600" />
            <h4 className="text-xs font-mono font-bold uppercase text-zinc-800 tracking-wider">
              Resolution Action
            </h4>
          </div>
          <p className="text-sm text-zinc-600 leading-relaxed font-sans font-mono bg-green-50/20 p-2.5 border border-green-200/50 rounded text-xs">
            {postmortem.resolution}
          </p>
        </div>
      </div>

      {/* Detection & Timeline */}
      <div className="bg-white p-5 rounded-lg border border-zinc-200 shadow-xxs space-y-4">
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <Compass className="w-4 h-4 text-zinc-700" />
            <h4 className="text-xs font-mono font-bold uppercase text-zinc-800 tracking-wider">
              Detection Mechanisms
            </h4>
          </div>
          <p className="text-sm text-zinc-600 leading-relaxed font-sans">{postmortem.detection}</p>
        </div>

        <div className="border-t border-zinc-100 pt-4">
          <div className="flex items-center gap-2 mb-3">
            <Clock className="w-4 h-4 text-zinc-700" />
            <h4 className="text-xs font-mono font-bold uppercase text-zinc-800 tracking-wider">
              Event Chronology
            </h4>
          </div>
          <div className="space-y-2 font-mono text-xs">
            {postmortem.timeline.map((line, idx) => (
              <div key={idx} className="flex gap-2.5 items-start p-2 hover:bg-zinc-50 border border-transparent hover:border-zinc-100 rounded">
                <ChevronRight className="w-4 h-4 text-zinc-400 shrink-0 mt-0.5" />
                <span className="text-zinc-600 leading-relaxed">{line}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Contributing Factors & Follow-up Actions */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        <div className="bg-white p-4 rounded-lg border border-zinc-200 shadow-xxs">
          <h4 className="text-xs font-mono font-bold uppercase text-zinc-800 tracking-wider mb-3">
            Contributing Factors
          </h4>
          <ul className="space-y-2 text-xs text-zinc-600">
            {postmortem.contributingFactors.map((factor, idx) => (
              <li key={idx} className="flex gap-2 items-start font-sans">
                <span className="text-zinc-400 font-mono mt-0.5">•</span>
                <span>{factor}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className="bg-white p-4 rounded-lg border border-zinc-200 shadow-xxs">
          <h4 className="text-xs font-mono font-bold uppercase text-zinc-800 tracking-wider mb-3 text-green-800">
            Preventative Follow-up Actions
          </h4>
          <ul className="space-y-2 text-xs text-zinc-600">
            {postmortem.followUpActions.map((action, idx) => (
              <li key={idx} className="flex gap-2 items-start font-sans">
                <span className="text-green-500 font-mono mt-0.5">[✓]</span>
                <span>{action}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  );
};
